// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type CodeChunk struct {
	ID         pgtype.UUID
	SymbolName string
	SymbolType string
	FilePath   string
	StartLine  int32
	EndLine    int32
	Content    string
	Doc        pgtype.Text
	Embedding  pgvector.Vector
	TokenCount int32
	Sha256     string
	CreatedAt  pgtype.Timestamptz
}
